[package]
name = "r-smhup_1"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
precompile = { path = "precompile" }
amethyst = "0.13"
objc = "=0.2.6"
serde = "1.0"
serde_derive = "1.0"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
